tweask

diff --git a/link/bashrc b/link/bashrc
--- a/link/bashrc
+++ b/link/bashrc
@@ -52,6 +52,24 @@ alias grep='grep --color=auto'
 # match all files and zero or more directories and subdirectories.
 #shopt -s globstar
 
+function errexit() {
+  local err=$?
+  set +o xtrace
+  local code="${1:-1}"
+  echo "Error in ${BASH_SOURCE[1]}:${BASH_LINENO[0]}. '${BASH_COMMAND}' exited with status $err"
+  # Print out the stack trace described by $function_stack
+  if [ ${#FUNCNAME[@]} -gt 2 ]
+  then
+    echo "Call tree:"
+    for ((i=1;i<${#FUNCNAME[@]}-1;i++))
+    do
+      echo " $i: ${BASH_SOURCE[$i+1]}:${BASH_LINENO[$i]} ${FUNCNAME[$i]}(...)"
+    done
+  fi
+  echo "Exiting with status ${code}"
+  exit "${code}"
+}
+
 ## PS1
 # I put PS1 in a sepeerate file
 if [ -f ~/.bash_PS1 ]; then
